# Generated by Django 4.1.1 on 2022-10-14 12:56

from django.db import migrations, models
import django.db.models.deletion
import todo_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_task_description_alter_task_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[todo_app.validators.min_length_validation])),
                ('specification', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('project_deadline', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='todo_app.project'),
        ),
    ]
